name: CI Pipeline - DevOps Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # =========================
      # STAGE 1: CHECKOUT CODE
      # =========================
      - name: Checkout source code
        uses: actions/checkout@v4

      # =========================
      # STAGE 2: SONARCLOUD SCAN
      # =========================
      - name: SonarCloud Code Quality Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=Vivaanjain02_Devops
            -Dsonar.organization=vivaanjain02
            -Dsonar.sources=.

      # =========================
      # STAGE 3: DOCKER BUILD
      # =========================
      - name: Build Docker image
        run: |
          docker build -t devops-static-app .

      # =========================
      # STAGE 4: RUN + SMOKE TEST
      # =========================
      - name: Run container and smoke test
        run: |
          docker rm -f test-app || true
          docker run -d -p 8080:80 --name test-app devops-static-app
          sleep 5
          curl -f http://localhost:8080

      # =========================
      # STAGE 5: CLEANUP
      # =========================
      - name: Cleanup container
        if: always()
        run: |
          docker rm -f test-app || true

      # =========================
      # STAGE 6: MONITORING READY
      # =========================
      - name: Monitoring Ready
        run: |
          echo "Application is ready for Prometheus & Grafana monitoring"
