name: CI Pipeline - Static App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t devops-static-app .

      - name: Run container (smoke test)
        run: |
          docker run -d -p 8080:80 --name test-container devops-static-app
          sleep 5
          curl -f http://localhost:8080
